version: '3.8'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command:
      - "start-dev"
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks
    networks:
      - backend

  app:
    build: .
    container_name: springboot_app
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasks?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend

networks:
  backend:
    driver: bridge
