spring:
      application:
        name: secure-task-manager-api
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://localhost:8080/realms/task-manager-api
              jwk-set-uri: http://localhost:8080/realms/task-manager-api/protocol/openid-connect/certs
      datasource:
        url: jdbc:mysql://localhost:3306/tasks?createDatabaseIfNoExist=true
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: create-drop
        database: mysql
        show-sql: true


server:
  port: 8081


jwt:
  auth:
    converter:
      resource-id: task-manager-api-client
      principle-attribute: preferred_username